.TH DVDSTYLER 1 "October 30, 2008"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dvdstyler \- cross platform DVD authoring system for Video DVD production
.SH SYNOPSIS
.B dvdstyler
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B dvdstyler
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBDVDStyler\fP is an authoring program to produce Video DVDs.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-e, \-\-stderr
Write log messages to standard error.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-s, \-\-start
Automatically starts the generation and burning.
.TP
.B \-v, \-\-version
Show version of program.
.SH AUTHOR
DVDStyler was written by Alex Thuering <alex.thuering@web.de>.
.PP
This manual page was written by Fabrice Coutadeur <coutadeurf@gmail.com>
and Uwe Bugla <uwe.bugla@gmx.de> for the Debian project of DVDStyler.
